// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJwl8lf0TXLvvtLKOsXAjQ7VSDdNURTSw',
    appId: '1:732112393517:web:f718c6fbcd830adc336fa4',
    messagingSenderId: '732112393517',
    projectId: 'sociality-f3dd1',
    authDomain: 'sociality-f3dd1.firebaseapp.com',
    storageBucket: 'sociality-f3dd1.appspot.com',
    measurementId: 'G-90JHC9FQ4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VOtoxOpuIR-rWn5af-t8EJtPHJi6aAI',
    appId: '1:732112393517:android:079c4affa81bf009336fa4',
    messagingSenderId: '732112393517',
    projectId: 'sociality-f3dd1',
    storageBucket: 'sociality-f3dd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmGj0LmpOq7jYpj7f8XA0Jiqu64QvboA',
    appId: '1:732112393517:ios:55a8c6841a086dd5336fa4',
    messagingSenderId: '732112393517',
    projectId: 'sociality-f3dd1',
    storageBucket: 'sociality-f3dd1.appspot.com',
    iosClientId: '732112393517-cp94ra29icq80dkiealv29b38m6jcggl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fApp',
  );
}
