// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxKlT0YUmcsC-mcaPY-tH-3RUCL2fxcxw',
    appId: '1:133115175036:web:81dd75048e968407c669f9',
    messagingSenderId: '133115175036',
    projectId: 'socialite-2bd7a',
    authDomain: 'socialite-2bd7a.firebaseapp.com',
    storageBucket: 'socialite-2bd7a.appspot.com',
    measurementId: 'G-75CVQCBWWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCitNXb479NPTe5tkx8z-RTc1ABCIHfgoo',
    appId: '1:133115175036:android:8df79b0da830b8f4c669f9',
    messagingSenderId: '133115175036',
    projectId: 'socialite-2bd7a',
    storageBucket: 'socialite-2bd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYPX8_lK1UxWOS3Y4I0emHwmOCOet2_Fw',
    appId: '1:133115175036:ios:6eddcf7dc5964118c669f9',
    messagingSenderId: '133115175036',
    projectId: 'socialite-2bd7a',
    storageBucket: 'socialite-2bd7a.appspot.com',
    iosClientId: '133115175036-4283b2dbs85l04pourel21a9v72ek61b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fApp',
  );
}
