// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJUmxgzryb0abFWxmwl18BpS-n9DbEnk',
    appId: '1:1003923502268:web:73fb47a334b62c08f3ccb9',
    messagingSenderId: '1003923502268',
    projectId: 'f-app-e69d9',
    authDomain: 'f-app-e69d9.firebaseapp.com',
    storageBucket: 'f-app-e69d9.appspot.com',
    measurementId: 'G-V1F8H90EVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYE_FrcJjUO7SI4yqd79XhOUEKMusbFA',
    appId: '1:1003923502268:android:7b746d42898e1bdaf3ccb9',
    messagingSenderId: '1003923502268',
    projectId: 'f-app-e69d9',
    storageBucket: 'f-app-e69d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CV0tIz4-NNfPwlvjRA0aOCt7V4KU5Ao',
    appId: '1:1003923502268:ios:7ce43c916cdd6df0f3ccb9',
    messagingSenderId: '1003923502268',
    projectId: 'f-app-e69d9',
    storageBucket: 'f-app-e69d9.appspot.com',
    androidClientId: '1003923502268-368mhf8ou051ufhc570tqnpdi97vb0ti.apps.googleusercontent.com',
    iosClientId: '1003923502268-d37p4n5t88879s3qsuivl060djje22e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fApp',
  );
}
